name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.4"
      - name: Run tests
        run: lua tests/check.lua
